# Generated by Django 4.2.1 on 2023-06-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_game"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rolls",
            new_name="Roles",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="roll",
            new_name="role",
        ),
        migrations.RemoveField(
            model_name="game",
            name="roll_of_1",
        ),
        migrations.RemoveField(
            model_name="game",
            name="roll_of_2",
        ),
    ]
